"""init2

Revision ID: 257aca06850d
Revises: 2230a2fe5ff8
Create Date: 2024-09-19 00:49:41.045275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257aca06850d'
down_revision = '2230a2fe5ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
